### ISSUE TITLE
Steps I had to take in order to run this project on my machine locally

### ISSUE THREAD

**Issue by Maurdekye** [Newbeeer/Poisson_flow#4]
My environment already has Cuda 11.8 installed.
1. Clone the repository locally
2. Create a new conda environment with `python==3.9.13`
3. Modify requirements.txt to remove the requirement for `absl==0.0`
~~4. Modify requirements.txt to remove the `+cu116` suffixes for the `torch` and `torchvision` packages~~ This change is part of why I was facing issues
5. `pip install -r requirements.txt`
6. Install tensorflow 2.10.0 over the version specified in the requirements.txt in order to support Tensorflow Probability
7. Install ninja to load C++ extensions
8. Downloaded the zip `cifar10_ddpmpp.zip` from the linked google drive and extracted the `checkpoint_500000.pth` model file to the directory `./workdir/checkpoints`
9. `pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

When running the following command:
`python main.py --config ./configs/poisson/cifar10_ddpmpp.py --mode eval --workdir ./workdir`

I get this console output, and no files are generated:
```
2022-10-27 11:04:29.246149: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 11:04:29.348970: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-27 11:04:29.766714: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-27 11:04:29.766792: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-27 11:04:29.766821: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
WARNING:tensorflow:From /home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.

WARNING:tensorflow:From /home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.

/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2022-10-27 11:05:10.565954: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-10-27 11:05:10.688136: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-10-27 11:05:10.688179: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I1027 11:05:10.730823 140021456623424 xla_bridge.py:345] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I1027 11:05:10.965448 140021456623424 xla_bridge.py:345] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter CUDA Host
I1027 11:05:10.965839 140021456623424 xla_bridge.py:345] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I1027 11:05:10.966645 140021456623424 dataset_info.py:439] Load dataset info from /home/<username>/tensorflow_datasets/cifar10/3.0.2
W1027 11:05:10.968783 140021456623424 options.py:588] options.experimental_threading is deprecated. Use options.threading instead.
W1027 11:05:10.968874 140021456623424 options.py:588] options.experimental_threading is deprecated. Use options.threading instead.
I1027 11:05:10.969661 140021456623424 dataset_builder.py:369] Reusing dataset cifar10 (/home/<username>/tensorflow_datasets/cifar10/3.0.2)
I1027 11:05:10.969773 140021456623424 logging_logger.py:44] Constructing tf.data.Dataset cifar10 for split train, from /home/<username>/tensorflow_datasets/cifar10/3.0.2
2022-10-27 11:05:10.972231: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
W1027 11:05:11.132379 140021456623424 options.py:588] options.experimental_threading is deprecated. Use options.threading instead.
W1027 11:05:11.132514 140021456623424 options.py:588] options.experimental_threading is deprecated. Use options.threading instead.
I1027 11:05:11.132633 140021456623424 dataset_builder.py:369] Reusing dataset cifar10 (/home/<username>/tensorflow_datasets/cifar10/3.0.2)
I1027 11:05:11.132725 140021456623424 logging_logger.py:44] Constructing tf.data.Dataset cifar10 for split test, from /home/<username>/tensorflow_datasets/cifar10/3.0.2
--- sampling eps: 0.001
I1027 11:05:12.034308 140021456623424 resolver.py:105] Using /tmp/tfhub_modules to cache modules.
I1027 11:05:13.515388 140021456623424 run_lib.py:308] begin checkpoint: 8
./workdir/checkpoints/checkpoint_400000.pth does not exist
./workdir/checkpoints/checkpoint_450000.pth does not exist
loading from  ./workdir/checkpoints/checkpoint_500000.pth
./workdir/checkpoints/checkpoint_550000.pth does not exist
./workdir/checkpoints/checkpoint_600000.pth does not exist
./workdir/checkpoints/checkpoint_650000.pth does not exist
./workdir/checkpoints/checkpoint_700000.pth does not exist
./workdir/checkpoints/checkpoint_750000.pth does not exist
./workdir/checkpoints/checkpoint_800000.pth does not exist
./workdir/checkpoints/checkpoint_850000.pth does not exist
./workdir/checkpoints/checkpoint_900000.pth does not exist
./workdir/checkpoints/checkpoint_950000.pth does not exist
./workdir/checkpoints/checkpoint_1000000.pth does not exist
./workdir/checkpoints/checkpoint_1050000.pth does not exist
./workdir/checkpoints/checkpoint_1100000.pth does not exist
./workdir/checkpoints/checkpoint_1150000.pth does not exist
./workdir/checkpoints/checkpoint_1200000.pth does not exist
./workdir/checkpoints/checkpoint_1250000.pth does not exist
./workdir/checkpoints/checkpoint_1300000.pth does not exist
```

**Comment by Newbeeer** [comment]
Hi,

Please add `--config.eval.enable_sampling` and  `--config.eval.save_images` in your command line for sampling & visualization. See the Readme/checkpoint section for detailed instructions.

**Comment by Maurdekye** [comment]
Thanks for the reply; I had to install the appropriate version of pytorch into my conda environment;
`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge`
afterwards, running the command with the added args you specified caused this strange torch error:

```
2022-10-27 14:23:01.666306: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 14:23:01.791125: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-27 14:23:02.235650: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-27 14:23:02.235723: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-27 14:23:02.235748: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
WARNING:tensorflow:From /home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.

WARNING:tensorflow:From /home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/tensorflow_gan/python/estimator/tpu_gan_estimator.py:42: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.

No CUDA runtime is found, using CUDA_HOME='/usr'
Traceback (most recent call last):
  File "/mnt/c/AI Image gen/Poisson_flow/main.py", line 18, in <module>
    import run_lib
  File "/mnt/c/AI Image gen/Poisson_flow/run_lib.py", line 30, in <module>
    from models import ncsnv2, ncsnpp
  File "/mnt/c/AI Image gen/Poisson_flow/models/ncsnpp.py", line 18, in <module>
    from . import utils, layers, layerspp, normalization
  File "/mnt/c/AI Image gen/Poisson_flow/models/layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "/mnt/c/AI Image gen/Poisson_flow/models/up_or_down_sampling.py", line 10, in <module>
    from op import upfirdn2d
  File "/mnt/c/AI Image gen/Poisson_flow/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/mnt/c/AI Image gen/Poisson_flow/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2014, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/<username>/miniconda3/envs/poisson/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

I don't know if your code is responsible, and I found a similar error on this git issue discussion: https://github.com/pytorch/extension-cpp/issues/71

---

On further experimentation and research it seems my cuda toolkit installation might be to blame, as `torch.cuda.is_available()` returns `False`.

**Comment by Newbeeer** [comment]
I guess you may need to install pytorch with compatible CUDA Version with your local GPU CUDA Version. For your reference, our code can successfully run on Python 3.9.12 with CUDA Version 11.6 + A100 / CUDA Version 11.4 + RTX 8000 / CUDA Version 11.4 + GeForce GPUs.

**Comment by Maurdekye** [comment]
After reinstalling my cuda toolkit, torch, and torchvision with the correct cuda support enabled (I should have left the +cu116 suffixes on), I was able to run the program and generate a sample output.

**Comment by Newbeeer** [comment]
Sounds good! Feel free to reach out for other issues!
